language: python

python:
	-2.7
	-3.5
	-3.6

branches:
	only:
		- master

install:
	- pip install coverage
	- pip install coveralls
	- pip install flake8
	- pip install -r requirements.txt

before_script:
	- "flake8 news-article-nlp"

script:
	- coverage run -m unittest

after_success:
	- coverage report
	- coveralls

after_failure:
	- mailx -s "Failed CI" pcwright@uw.edu
	- mailx -s "Failed CI" yd4wh@uw.edu