language: python

python:
    - 3.2
    - 3.3
    - 3.4 
    - 3.5
    - 3.6

branches:
    only:
        - master

install:
    - pip install coverage
    - pip install coveralls
    - pip install flake8
    - pip install pylint
    - pip install -r requirements.txt

before_script:
    - python setup.py
    - flake8 news-article-nlp || echo "flake8 may have failed. Expand to see flake8 messages."
    - pylint news-article-nlp || echo "pylint may have failed. Expand to see pylint messages."

script:
    - coverage run -m unittest discover news-article-nlp/tests

after_success:
    - coverage report
    - coveralls

after_failure:
    - mailx -s "Failed CI" pcwright@uw.edu
    - mailx -s "Failed CI" yd4wh@uw.edu
